# Generated by Django 4.2.4 on 2023-08-26 13:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("product_module", "0003_productvisit"),
    ]

    operations = [
        migrations.AddField(
            model_name="productcategory",
            name="parent_category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="product_module.productcategory",
            ),
        ),
    ]
