version: v2.20.3

services:
  db:
    container_name: postgres
    image: postgres:15.3
    env_file:
      - .env
    networks:
      - main
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=e_shop
      - POSTGRES_USER=hooman
      - POSTGRES_PASSWORD=hooman1380
  app:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
#    command: sh -c "python manage.py migrate && gunicorn A.wsgi -b 0.0.0.0:8000"
    container_name: app
    volumes:
      - .:/code/
    depends_on:
      - db
    environment:
      DJANGO_SETTINGS_MODULE: 'e_shop_project.settings'
    expose:
      - "8000"
    networks:
      - main
    restart: always

networks:
  main:
    name: main
volumes:
  postgres_data:
    name: postgres_data
