# Generated by Django 4.1.2 on 2023-05-18 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=200, verbose_name='عنوان')),
                ('url', models.URLField(blank=True, max_length=400, null=True, verbose_name='آدرس بنر')),
                ('image', models.ImageField(upload_to='site/site_banner', verbose_name='تصویر بنر')),
                ('is_active', models.BooleanField(verbose_name='فعال / غیر فعال')),
                ('position', models.CharField(choices=[('product_list', 'صفحه ی لیست محصولات'), ('product_detail', 'صفحه ی جزییات محصولات'), ('about_us', 'صفحه ی درباره ما'), ('index_page', 'صفحه ی اصلی سایت'), ('category_list', 'صفحه لیست دسته بندی'), ('category_detail', 'صفحه جزییات دسته بندی')], max_length=200, verbose_name='جایگاه نمایشی')),
            ],
            options={
                'verbose_name': 'بنر تبلیغاتی',
                'verbose_name_plural': 'بنر های تبلیغاتی',
            },
        ),
    ]
