# Generated by Django 4.2.4 on 2023-08-15 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_module', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitebanner',
            name='position',
            field=models.CharField(choices=[('product_list', 'صفحه ی لیست محصولات'), ('product_detail', 'صفحه ی جزییات محصولات'), ('about_us', 'صفحه ی درباره ما'), ('index_page', 'صفحه ی اصلی سایت'), ('category_list', 'صفحه لیست دسته بندی محصولات'), ('category_detail', 'صفحه جزییات دسته بندی محصولات')], max_length=200, verbose_name='جایگاه نمایشی'),
        ),
    ]
