# Generated by Django 4.1.2 on 2023-05-11 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact_module', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(db_index=True, max_length=200, verbose_name='نام تیم')),
                ('phone_team', models.PositiveIntegerField(verbose_name='تلفن گروه')),
                ('address', models.TextField(verbose_name='آدرس مجموعه')),
                ('logo_image', models.ImageField(upload_to='contact_us/about_us', verbose_name='تصویر لوگو')),
                ('about_team', models.TextField(verbose_name='توضیحات درباره تیم')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال / غیر فعال')),
            ],
            options={
                'verbose_name': 'فرم درباره ما',
                'verbose_name_plural': 'فرم های درباره ما',
            },
        ),
    ]
