# Generated by Django 4.1.2 on 2023-05-10 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_module', '0002_user_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='Address',
            field=models.TextField(blank=True, null=True),
        ),
    ]
